# Generated by Django 3.0.5 on 2020-04-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
                ('nombre', models.CharField(max_length=45, verbose_name='Materia')),
                ('carga', models.FloatField(verbose_name='Carga')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Tipo de archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Tipo de tramite')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=45, verbose_name='Rol')),
                ('correo', models.CharField(max_length=45, verbose_name='Correo')),
                ('contrasena', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('paterno', models.CharField(max_length=45, verbose_name='Paterno')),
                ('materno', models.CharField(max_length=45, verbose_name='Materno')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('nacimiento', models.DateField()),
                ('telefono', models.IntegerField(null=True, verbose_name='Teléfono')),
                ('domicilio', models.CharField(max_length=150, verbose_name='Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appstart.Usuario')),
                ('folio', models.CharField(max_length=25, verbose_name='Folio')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appstart.Usuario')),
                ('boleta', models.CharField(max_length=10, verbose_name='Boleta')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('ciclo_escolar', models.CharField(max_length=6, verbose_name='Ciclo escolar')),
                ('estatus', models.CharField(max_length=25, verbose_name='Estatus')),
                ('documento', models.BinaryField()),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('tipo_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstart.Tipo_tramite')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstart.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='ETS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.BooleanField()),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstart.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo_adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.BinaryField()),
                ('tipo_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstart.Tipo_archivo')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstart.Tramite')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno_ETS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estatus', models.CharField(max_length=25, verbose_name='Estatus')),
                ('ets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstart.ETS')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstart.Alumno')),
            ],
        ),
    ]
