# Generated by Django 3.0.5 on 2020-06-15 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoInstance',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appstart.Alumno')),
                ('boleta', models.CharField(max_length=10, verbose_name='Boleta')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='alumno_ets',
            name='ets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etss', to='appstart.ETS'),
        ),
        migrations.AlterField(
            model_name='archivo_adjunto',
            name='tipo_archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_archivos', to='appstart.Tipo_archivo'),
        ),
        migrations.AlterField(
            model_name='archivo_adjunto',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='appstart.Tramite'),
        ),
        migrations.AlterField(
            model_name='ets',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etss', to='appstart.Materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipo_archivo',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_tramites', to='appstart.Tipo_tramite'),
        ),
    ]
