# Generated by Django 3.0.5 on 2020-06-15 01:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0002_auto_20200614_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ets',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appstart.Alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ets',
            name='estatus',
            field=models.CharField(default='EN PROCESO', max_length=25, verbose_name='Estatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ets',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tramite',
            name='atributos_dictamen',
            field=jsonfield.fields.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=45, verbose_name='Correo'),
        ),
    ]
