# Generated by Django 3.0.5 on 2020-06-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0003_auto_20200614_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='documento',
            field=models.FileField(upload_to=''),
        ),
    ]
