# Generated by Django 3.0.5 on 2020-06-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0004_auto_20200614_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='documento',
            new_name='documento_firmado',
        ),
        migrations.AlterField(
            model_name='archivo_adjunto',
            name='documento',
            field=models.FileField(upload_to=''),
        ),
    ]
