# Generated by Django 3.0.5 on 2020-06-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0005_auto_20200614_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
    ]
