# Generated by Django 3.0.5 on 2020-06-15 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0007_usuario_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
    ]
