# Generated by Django 3.0.5 on 2020-06-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0008_remove_usuario_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='', max_length=45, verbose_name='Contraseña'),
            preserve_default=False,
        ),
    ]
