# Generated by Django 3.0.5 on 2020-06-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0009_usuario_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='otro',
            field=models.CharField(default='', max_length=150, verbose_name='Otro'),
            preserve_default=False,
        ),
    ]
