# Generated by Django 3.0.5 on 2020-06-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0010_usuario_otro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='otro',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(blank=True, max_length=45, verbose_name='Contraseña'),
        ),
    ]
