# Generated by Django 3.0.5 on 2020-06-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0011_auto_20200615_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=45, null=True, verbose_name='Contraseña'),
        ),
    ]
