# Generated by Django 3.0.5 on 2020-06-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0012_auto_20200615_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno_ets',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='alumno_ets',
            name='fecha',
        ),
    ]
