# Generated by Django 3.0.5 on 2020-06-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0014_auto_20200621_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ets',
            name='alumno',
        ),
    ]
