# Generated by Django 3.0.5 on 2020-06-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstart', '0015_remove_ets_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='', max_length=45, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
